spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.140.128:3307/jdbc
    driver-class-name: com.mysql.jdbc.Driver
    schema:
      - classpath:department.sql
